/**
 * AUTO-GENERATED by generate-composition — Private Investment Analyzer
 * Custom Remotion composition simulating the app's actual UI.
 * No screenshots — every component is built from scratch based on the codebase.
 */
import React from 'react';
import {
  AbsoluteFill,
  Sequence,
  useCurrentFrame,
  useVideoConfig,
  spring,
  interpolate,
} from 'remotion';

// ─── Brand tokens ─────────────────────────────────────────────────────────────
const BG        = '#0a0a0f';
const SECONDARY = '#12121f';
const ACCENT    = '#6366f1';
const TEXT      = '#f0f0f5';
const MUTED     = '#8888a8';
const BORDER    = 'rgba(99,102,241,0.2)';
const SUCCESS   = '#22c55e';
const DANGER    = '#ef4444';

// ─── Scene durations ──────────────────────────────────────────────────────────
const D_HOOK        = 90;
const D_SEARCH      = 240;
const D_HOLDINGS    = 240;
const D_BDC         = 180;
const D_COMPARISON  = 150;
const D_ENDCARD     = 120;

export const GENERATED_DURATION = D_HOOK + D_SEARCH + D_HOLDINGS + D_BDC + D_COMPARISON + D_ENDCARD;
export const GENERATED_FPS      = 30;
export const GENERATED_WIDTH    = 1920;
export const GENERATED_HEIGHT   = 1080;

// ─── Shared component: AppChrome ──────────────────────────────────────────────
// Simulates the dark web app shell (nav bar + content area)

interface AppChromeProps {
  activeTab: string;
  children: React.ReactNode;
}

const AppChrome: React.FC<AppChromeProps> = ({ activeTab, children }) => {
  const navStyle: React.CSSProperties = {
    height: 52,
    background: SECONDARY,
    borderBottom: `1px solid ${BORDER}`,
    display: 'flex',
    alignItems: 'center',
    padding: '0 32px',
    gap: 32,
    flexShrink: 0,
  };
  const logoStyle: React.CSSProperties = {
    color: ACCENT,
    fontSize: 15,
    fontWeight: 700,
    fontFamily: 'monospace',
    letterSpacing: 1,
    marginRight: 16,
  };
  const tabStyle = (active: boolean): React.CSSProperties => ({
    fontSize: 14,
    fontFamily: 'sans-serif',
    color: active ? TEXT : MUTED,
    borderBottom: active ? `2px solid ${ACCENT}` : '2px solid transparent',
    paddingBottom: 2,
    cursor: 'default',
    fontWeight: active ? 600 : 400,
  });
  const shellStyle: React.CSSProperties = {
    position: 'absolute',
    inset: 0,
    background: BG,
    display: 'flex',
    flexDirection: 'column',
    borderRadius: 12,
    overflow: 'hidden',
    border: `1px solid ${BORDER}`,
  };
  return (
    <div style={shellStyle}>
      <div style={navStyle}>
        <span style={logoStyle}>📊 NPORT Analyzer</span>
        {['NPORT-P Search', 'BDC 10-Q / 10-K', 'Cross-Fund'].map((tab) => (
          <span key={tab} style={tabStyle(tab === activeTab)}>{tab}</span>
        ))}
      </div>
      <div style={{ flex: 1, overflow: 'hidden', position: 'relative' }}>{children}</div>
    </div>
  );
};

// ─── Shared component: SearchBar ──────────────────────────────────────────────

interface SearchBarProps {
  typedText: string;
  showCursor: boolean;
  focused: boolean;
  placeholder: string;
}

const SearchBar: React.FC<SearchBarProps> = ({ typedText, showCursor, focused, placeholder }) => {
  const wrapStyle: React.CSSProperties = {
    display: 'flex',
    gap: 16,
    width: '100%',
    maxWidth: 820,
  };
  const inputStyle: React.CSSProperties = {
    flex: 1,
    height: 52,
    background: 'rgba(255,255,255,0.04)',
    border: `1.5px solid ${focused ? ACCENT : 'rgba(255,255,255,0.12)'}`,
    borderRadius: 10,
    padding: '0 20px',
    color: TEXT,
    fontSize: 18,
    fontFamily: 'sans-serif',
    display: 'flex',
    alignItems: 'center',
    boxShadow: focused ? `0 0 0 3px ${ACCENT}22` : 'none',
  };
  const btnStyle: React.CSSProperties = {
    height: 52,
    padding: '0 32px',
    background: ACCENT,
    border: 'none',
    borderRadius: 10,
    color: '#fff',
    fontSize: 16,
    fontWeight: 600,
    fontFamily: 'sans-serif',
    cursor: 'default',
    whiteSpace: 'nowrap',
  };
  const cursorStyle: React.CSSProperties = {
    display: 'inline-block',
    width: 2,
    height: 20,
    background: ACCENT,
    marginLeft: 2,
    verticalAlign: 'middle',
  };
  return (
    <div style={wrapStyle}>
      <div style={inputStyle}>
        <span style={{ color: typedText ? TEXT : MUTED }}>
          {typedText || placeholder}
        </span>
        {showCursor && <span style={cursorStyle} />}
      </div>
      <button style={btnStyle}>Search EDGAR →</button>
    </div>
  );
};

// ─── Shared component: HoldingsRow ────────────────────────────────────────────

interface HoldingsRowData {
  fund: string;
  cusip: string;
  shares: string;
  fairValue: string;
  date: string;
}

interface HoldingsRowProps {
  row: HoldingsRowData;
  s: number; // spring value 0→1
  accent?: boolean;
}

const HoldingsRow: React.FC<HoldingsRowProps> = ({ row, s, accent }) => {
  const rowStyle: React.CSSProperties = {
    display: 'flex',
    alignItems: 'center',
    padding: '14px 24px',
    borderBottom: `1px solid rgba(255,255,255,0.04)`,
    opacity: s,
    transform: `translateX(${(1 - s) * 24}px)`,
    background: accent ? 'rgba(99,102,241,0.06)' : 'transparent',
  };
  const cellStyle = (w: string | number, align?: string): React.CSSProperties => ({
    width: typeof w === 'string' ? w : undefined,
    flex: typeof w === 'number' ? w : undefined,
    fontSize: 15,
    fontFamily: 'sans-serif',
    color: TEXT,
    textAlign: (align as React.CSSProperties['textAlign']) ?? 'left',
  });
  const monoStyle: React.CSSProperties = {
    ...cellStyle('160px'),
    fontFamily: 'monospace',
    color: MUTED,
    fontSize: 13,
  };
  const valueStyle: React.CSSProperties = {
    ...cellStyle('140px', 'right'),
    color: SUCCESS,
    fontWeight: 600,
  };
  return (
    <div style={rowStyle}>
      <div style={cellStyle(1)}>{row.fund}</div>
      <div style={monoStyle}>{row.cusip}</div>
      <div style={{ ...cellStyle('130px', 'right'), fontFamily: 'monospace', color: MUTED }}>{row.shares}</div>
      <div style={valueStyle}>{row.fairValue}</div>
      <div style={{ ...cellStyle('120px', 'right'), color: MUTED, fontSize: 13, fontFamily: 'monospace' }}>{row.date}</div>
    </div>
  );
};

// ─── Scene 1: Hook ────────────────────────────────────────────────────────────

const SceneHook: React.FC<{ frame: number; fps: number }> = ({ frame, fps }) => {
  const s1 = spring({ frame: Math.max(0, frame - 0),  fps, config: { damping: 14, stiffness: 120 } });
  const s2 = spring({ frame: Math.max(0, frame - 10), fps, config: { damping: 14, stiffness: 120 } });
  const s3 = spring({ frame: Math.max(0, frame - 20), fps, config: { damping: 14, stiffness: 120 } });
  const s4 = spring({ frame: Math.max(0, frame - 34), fps, config: { damping: 14, stiffness: 120 } });

  const containerStyle: React.CSSProperties = {
    position: 'absolute',
    inset: 0,
    background: `radial-gradient(ellipse 70% 60% at 50% 45%, rgba(99,102,241,0.2) 0%, ${BG} 70%)`,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 28,
  };
  const pillStyle: React.CSSProperties = {
    background: 'rgba(99,102,241,0.18)',
    border: `1px solid rgba(99,102,241,0.5)`,
    borderRadius: 24,
    padding: '6px 22px',
    color: ACCENT,
    fontSize: 14,
    fontFamily: 'monospace',
    letterSpacing: 3,
    textTransform: 'uppercase',
    opacity: s1,
    transform: `translateY(${(1 - s1) * 24}px)`,
  };
  const h1Style: React.CSSProperties = {
    fontSize: 88,
    fontWeight: 900,
    fontFamily: 'sans-serif',
    color: TEXT,
    textAlign: 'center',
    margin: 0,
    lineHeight: 1.05,
    letterSpacing: '-0.03em',
    opacity: s2,
    transform: `translateY(${(1 - s2) * 40}px)`,
  };
  const subtitleStyle: React.CSSProperties = {
    fontSize: 28,
    fontFamily: 'sans-serif',
    color: MUTED,
    textAlign: 'center',
    maxWidth: 860,
    lineHeight: 1.55,
    opacity: s3,
    transform: `translateY(${(1 - s3) * 28}px)`,
  };
  const badgesStyle: React.CSSProperties = {
    display: 'flex',
    gap: 14,
    opacity: s4,
    transform: `translateY(${(1 - s4) * 18}px)`,
  };
  const badgeStyle: React.CSSProperties = {
    background: SECONDARY,
    border: `1px solid ${BORDER}`,
    borderRadius: 8,
    padding: '9px 20px',
    color: MUTED,
    fontSize: 13,
    fontFamily: 'monospace',
  };

  return (
    <div style={containerStyle}>
      <div style={pillStyle}>SEC EDGAR · NPORT-P · BDC 10-Q</div>
      <h1 style={h1Style}>
        Which funds hold<br />
        <span style={{ color: ACCENT }}>Anthropic equity?</span>
      </h1>
      <p style={subtitleStyle}>
        Track how institutional funds mark the same private asset — across every NPORT-P filing
      </p>
      <div style={badgesStyle}>
        {['Cross-Fund Valuations', 'CUSIP Lookup', 'BDC 10-Q History'].map((b) => (
          <div key={b} style={badgeStyle}>{b}</div>
        ))}
      </div>
    </div>
  );
};

// ─── Scene 2: Search Demo ─────────────────────────────────────────────────────
// Animates: form slides in → user types "Anthropic" → clicks search → loading → result count

const SEARCH_QUERY = 'Anthropic';

const SceneSearch: React.FC<{ frame: number; fps: number }> = ({ frame, fps }) => {
  const formSpring = spring({ frame: Math.max(0, frame), fps, config: { damping: 16, stiffness: 100 } });

  // Typing animation: starts at frame 25, 3 chars per 8 frames
  const typingStart = 25;
  const charsTyped  = Math.min(SEARCH_QUERY.length, Math.floor(Math.max(0, frame - typingStart) * 0.35));
  const typedText   = SEARCH_QUERY.slice(0, charsTyped);
  const showCursor  = frame < 160 && Math.floor(frame / 15) % 2 === 0;

  // Click animation: frame 95
  const clickFrame   = Math.max(0, frame - 95);
  const clickScale   = frame >= 95 && frame < 115
    ? interpolate(clickFrame, [0, 6, 12], [1, 0.95, 1], { extrapolateRight: 'clamp' })
    : 1;
  const rippleOp   = frame >= 95 ? interpolate(clickFrame, [0, 18], [0.5, 0], { extrapolateRight: 'clamp' }) : 0;
  const rippleScale = frame >= 95 ? interpolate(clickFrame, [0, 18], [0.8, 2.0], { extrapolateRight: 'clamp' }) : 1;

  // Loading spinner: frames 110-155
  const isLoading   = frame >= 110 && frame < 155;
  const spinDeg     = frame >= 110 ? (frame - 110) * 12 : 0;

  // Result count badge: frame 155+
  const resultSpring = spring({ frame: Math.max(0, frame - 155), fps, config: { damping: 18, stiffness: 140 } });

  const outerStyle: React.CSSProperties = {
    position: 'absolute',
    inset: 0,
    background: BG,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '60px 80px',
    gap: 36,
  };
  const appWrapStyle: React.CSSProperties = {
    width: '100%',
    maxWidth: 1500,
    height: 600,
    opacity: formSpring,
    transform: `translateY(${(1 - formSpring) * 40}px) scale(${0.97 + formSpring * 0.03})`,
  };
  const headerStyle: React.CSSProperties = {
    color: TEXT,
    fontSize: 36,
    fontWeight: 700,
    fontFamily: 'sans-serif',
    textAlign: 'center',
    marginBottom: 0,
    opacity: formSpring,
    transform: `translateY(${(1 - formSpring) * 28}px)`,
  };
  const searchAreaStyle: React.CSSProperties = {
    padding: '48px 60px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 28,
    height: '100%',
  };
  const labelStyle: React.CSSProperties = {
    color: MUTED,
    fontSize: 15,
    fontFamily: 'sans-serif',
    textAlign: 'center',
  };

  return (
    <div style={outerStyle}>
      <div style={headerStyle}>
        Search <span style={{ color: ACCENT }}>SEC EDGAR NPORT-P</span> Filings
      </div>
      <div style={appWrapStyle}>
        <AppChrome activeTab="NPORT-P Search">
          <div style={searchAreaStyle}>
            <div style={labelStyle}>
              Find every mutual fund and BDC holding a private company
            </div>

            {/* Search bar with click/ripple */}
            <div style={{ position: 'relative', width: '100%', maxWidth: 820 }}>
              <div style={{ transform: `scale(${clickScale})`, transformOrigin: 'center' }}>
                <SearchBar
                  typedText={typedText}
                  showCursor={showCursor}
                  focused={frame >= 20 && frame < 160}
                  placeholder="Search by company name, CUSIP, or ticker..."
                />
              </div>
              {/* Ripple on click */}
              {frame >= 95 && (
                <div style={{
                  position: 'absolute',
                  right: 0,
                  top: '50%',
                  transform: `translate(0, -50%) scale(${rippleScale})`,
                  width: 120,
                  height: 52,
                  borderRadius: 10,
                  background: ACCENT,
                  opacity: rippleOp,
                  pointerEvents: 'none',
                }} />
              )}
            </div>

            {/* Filter pills */}
            <div style={{ display: 'flex', gap: 10, opacity: formSpring }}>
              {['Q3 2024', 'Q2 2024', 'Q1 2024', 'All periods'].map((f, i) => (
                <div key={f} style={{
                  padding: '6px 16px',
                  background: i === 0 ? 'rgba(99,102,241,0.2)' : 'rgba(255,255,255,0.04)',
                  border: `1px solid ${i === 0 ? ACCENT : 'rgba(255,255,255,0.1)'}`,
                  borderRadius: 20,
                  color: i === 0 ? ACCENT : MUTED,
                  fontSize: 13,
                  fontFamily: 'sans-serif',
                }}>{f}</div>
              ))}
            </div>

            {/* Loading state */}
            {isLoading && (
              <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 16 }}>
                <div style={{
                  width: 48,
                  height: 48,
                  borderRadius: '50%',
                  border: `3px solid ${BORDER}`,
                  borderTop: `3px solid ${ACCENT}`,
                  transform: `rotate(${spinDeg}deg)`,
                }} />
                <div style={{ color: MUTED, fontSize: 15, fontFamily: 'sans-serif' }}>
                  Querying SEC EDGAR EFTS...
                </div>
              </div>
            )}

            {/* Result count badge */}
            {frame >= 155 && (
              <div style={{
                display: 'flex',
                alignItems: 'center',
                gap: 16,
                background: 'rgba(34,197,94,0.1)',
                border: '1px solid rgba(34,197,94,0.3)',
                borderRadius: 12,
                padding: '16px 28px',
                opacity: resultSpring,
                transform: `translateY(${(1 - resultSpring) * 20}px) scale(${0.95 + resultSpring * 0.05})`,
              }}>
                <div style={{ color: SUCCESS, fontSize: 32, fontWeight: 800, fontFamily: 'sans-serif' }}>13</div>
                <div>
                  <div style={{ color: TEXT, fontSize: 16, fontWeight: 600, fontFamily: 'sans-serif' }}>
                    institutional funds found
                  </div>
                  <div style={{ color: MUTED, fontSize: 13, fontFamily: 'monospace' }}>
                    holding Anthropic across NPORT-P filings · Q3 2024
                  </div>
                </div>
              </div>
            )}
          </div>
        </AppChrome>
      </div>
    </div>
  );
};

// ─── Scene 3: Holdings Table ──────────────────────────────────────────────────

const HOLDINGS: HoldingsRowData[] = [
  { fund: 'Tiger Global Growth Fund IV',   cusip: '03664L102', shares: '1,250,000',  fairValue: '$12.5M',  date: 'Sep 2024' },
  { fund: 'Coatue Management LLC',         cusip: '03664L102', shares: '850,000',    fairValue: '$8.5M',   date: 'Sep 2024' },
  { fund: 'Andreessen Horowitz Fund IX',   cusip: '03664L102', shares: '620,000',    fairValue: '$6.2M',   date: 'Sep 2024' },
  { fund: 'Sequoia Capital Growth III',    cusip: '03664L102', shares: '540,000',    fairValue: '$5.4M',   date: 'Sep 2024' },
  { fund: 'Greenoaks Capital Partners',    cusip: '03664L102', shares: '420,000',    fairValue: '$4.2M',   date: 'Jun 2024' },
  { fund: 'TCV XI (Technology Crossover)', cusip: '03664L102', shares: '380,000',    fairValue: '$3.8M',   date: 'Jun 2024' },
];

const SceneHoldings: React.FC<{ frame: number; fps: number }> = ({ frame, fps }) => {
  const headerSpring = spring({ frame: Math.max(0, frame), fps, config: { damping: 16, stiffness: 110 } });

  const outerStyle: React.CSSProperties = {
    position: 'absolute',
    inset: 0,
    background: BG,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '40px 80px',
    gap: 28,
  };
  const appWrapStyle: React.CSSProperties = {
    width: '100%',
    maxWidth: 1500,
    height: 680,
    opacity: headerSpring,
    transform: `translateY(${(1 - headerSpring) * 30}px)`,
  };
  const tableHeaderStyle: React.CSSProperties = {
    display: 'flex',
    alignItems: 'center',
    padding: '14px 24px',
    borderBottom: `1px solid ${BORDER}`,
    background: 'rgba(99,102,241,0.05)',
  };
  const colLabelStyle = (w: string | number, align?: string): React.CSSProperties => ({
    width: typeof w === 'string' ? w : undefined,
    flex: typeof w === 'number' ? w : undefined,
    fontSize: 11,
    fontFamily: 'monospace',
    color: ACCENT,
    textTransform: 'uppercase',
    letterSpacing: 2,
    textAlign: (align as React.CSSProperties['textAlign']) ?? 'left',
  });
  const summaryBadgeStyle: React.CSSProperties = {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    opacity: headerSpring,
    transform: `translateY(${(1 - headerSpring) * 20}px)`,
  };

  return (
    <div style={outerStyle}>
      {/* Header row */}
      <div style={{ display: 'flex', alignItems: 'center', gap: 20, width: '100%', maxWidth: 1500 }}>
        <div style={{ ...summaryBadgeStyle, flex: 1 }}>
          <div>
            <div style={{ color: TEXT, fontSize: 26, fontWeight: 700, fontFamily: 'sans-serif' }}>
              Holdings by Fund — <span style={{ color: ACCENT }}>"Anthropic"</span>
            </div>
            <div style={{ color: MUTED, fontSize: 14, fontFamily: 'monospace', marginTop: 4 }}>
              NPORT-P filings · Q3 2024 · 13 institutional funds
            </div>
          </div>
        </div>
        <div style={{
          ...summaryBadgeStyle,
          background: 'rgba(34,197,94,0.1)',
          border: '1px solid rgba(34,197,94,0.25)',
          borderRadius: 10,
          padding: '10px 20px',
        }}>
          <span style={{ color: SUCCESS, fontSize: 28, fontWeight: 800, fontFamily: 'sans-serif' }}>13</span>
          <span style={{ color: MUTED, fontSize: 13, fontFamily: 'sans-serif' }}>funds holding equity</span>
        </div>
      </div>

      {/* Table */}
      <div style={appWrapStyle}>
        <AppChrome activeTab="NPORT-P Search">
          <div style={{ display: 'flex', flexDirection: 'column', height: '100%' }}>
            {/* Column headers */}
            <div style={tableHeaderStyle}>
              <div style={colLabelStyle(1)}>Fund Name</div>
              <div style={colLabelStyle('160px')}>CUSIP</div>
              <div style={colLabelStyle('130px', 'right')}>Shares</div>
              <div style={colLabelStyle('140px', 'right')}>Fair Value</div>
              <div style={colLabelStyle('120px', 'right')}>Filing Date</div>
            </div>

            {/* Data rows — staggered spring entrance */}
            <div style={{ flex: 1, overflow: 'hidden' }}>
              {HOLDINGS.map((row, i) => {
                const rowStart = 20 + i * 18;
                const s = spring({ frame: Math.max(0, frame - rowStart), fps, config: { damping: 18, stiffness: 140 } });
                return (
                  <HoldingsRow key={i} row={row} s={s} accent={i === 0} />
                );
              })}

              {/* "…and 7 more" footer */}
              {frame >= 150 && (
                <div style={{
                  padding: '12px 24px',
                  color: MUTED,
                  fontSize: 13,
                  fontFamily: 'monospace',
                  borderTop: `1px solid rgba(255,255,255,0.04)`,
                  opacity: interpolate(frame, [150, 170], [0, 1], { extrapolateRight: 'clamp' }),
                }}>
                  + 7 more funds · total exposure $59.3M · sorted by fair value ↓
                </div>
              )}
            </div>
          </div>
        </AppChrome>
      </div>
    </div>
  );
};

// ─── Scene 4: BDC Scene ───────────────────────────────────────────────────────

interface BdcRow {
  name: string;
  fileNum: string;
  period: string;
  filingType: string;
  status: string;
}

const BDC_ROWS: BdcRow[] = [
  { name: 'Ares Capital Corporation',      fileNum: '814-00254', period: 'Q2 2024', filingType: '10-Q', status: 'Portfolio' },
  { name: 'Blue Owl Capital Corporation',  fileNum: '814-01200', period: 'Q3 2024', filingType: '10-Q', status: 'Portfolio' },
  { name: 'Golub Capital BDC',             fileNum: '814-00989', period: 'Q2 2024', filingType: '10-Q', status: 'Portfolio' },
  { name: 'Prospect Capital Corp',         fileNum: '814-00500', period: 'Q3 2024', filingType: '10-Q', status: 'Portfolio' },
  { name: 'FS Investment Corporation',     fileNum: '814-00798', period: 'Q1 2024', filingType: '10-Q', status: 'Portfolio' },
];

const SceneBDC: React.FC<{ frame: number; fps: number }> = ({ frame, fps }) => {
  const headerSpring = spring({ frame: Math.max(0, frame), fps, config: { damping: 16, stiffness: 110 } });

  const outerStyle: React.CSSProperties = {
    position: 'absolute',
    inset: 0,
    background: BG,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '40px 80px',
    gap: 28,
  };
  const appWrapStyle: React.CSSProperties = {
    width: '100%',
    maxWidth: 1500,
    height: 660,
    opacity: headerSpring,
    transform: `translateY(${(1 - headerSpring) * 30}px)`,
  };
  const innerPadStyle: React.CSSProperties = {
    padding: '32px 40px',
    display: 'flex',
    flexDirection: 'column',
    gap: 24,
    height: '100%',
  };
  const sectionLabel: React.CSSProperties = {
    color: ACCENT,
    fontSize: 12,
    fontFamily: 'monospace',
    letterSpacing: 3,
    textTransform: 'uppercase',
  };

  return (
    <div style={outerStyle}>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 8, width: '100%', maxWidth: 1500, opacity: headerSpring, transform: `translateY(${(1-headerSpring)*20}px)` }}>
        <div style={{ color: ACCENT, fontSize: 13, fontFamily: 'monospace', letterSpacing: 3, textTransform: 'uppercase' }}>
          BDC Credit Analysis
        </div>
        <div style={{ color: TEXT, fontSize: 26, fontWeight: 700, fontFamily: 'sans-serif' }}>
          Business Development Companies — <span style={{ color: ACCENT }}>814- Auto-Identified</span>
        </div>
      </div>

      <div style={appWrapStyle}>
        <AppChrome activeTab="BDC 10-Q / 10-K">
          <div style={innerPadStyle}>
            <div style={sectionLabel}>Investment Company File Numbers (814-XXXXX)</div>

            {/* BDC rows */}
            <div style={{ display: 'flex', flexDirection: 'column', gap: 0, borderRadius: 10, overflow: 'hidden', border: `1px solid ${BORDER}` }}>
              {/* Header */}
              <div style={{ display: 'flex', padding: '12px 20px', background: 'rgba(99,102,241,0.08)', borderBottom: `1px solid ${BORDER}` }}>
                {['Company Name', 'File Number', 'Period', 'Filing', ''].map((h, i) => (
                  <div key={i} style={{
                    flex: i === 0 ? 2 : 1,
                    fontSize: 11,
                    fontFamily: 'monospace',
                    color: ACCENT,
                    textTransform: 'uppercase',
                    letterSpacing: 2,
                  }}>{h}</div>
                ))}
              </div>

              {BDC_ROWS.map((row, i) => {
                const s = spring({ frame: Math.max(0, frame - (20 + i * 16)), fps, config: { damping: 18, stiffness: 140 } });
                const rowStyle: React.CSSProperties = {
                  display: 'flex',
                  alignItems: 'center',
                  padding: '15px 20px',
                  borderBottom: i < BDC_ROWS.length - 1 ? `1px solid rgba(255,255,255,0.04)` : 'none',
                  opacity: s,
                  transform: `translateX(${(1 - s) * 20}px)`,
                };
                const fileNumStyle: React.CSSProperties = {
                  flex: 1,
                  fontFamily: 'monospace',
                  fontSize: 13,
                  color: ACCENT,
                  background: 'rgba(99,102,241,0.1)',
                  border: `1px solid rgba(99,102,241,0.25)`,
                  borderRadius: 6,
                  padding: '3px 10px',
                  display: 'inline-block',
                  width: 'fit-content',
                };
                const viewBtnStyle: React.CSSProperties = {
                  flex: 1,
                  fontSize: 12,
                  fontFamily: 'sans-serif',
                  color: ACCENT,
                  textDecoration: 'underline',
                  cursor: 'default',
                };
                return (
                  <div key={i} style={rowStyle}>
                    <div style={{ flex: 2, color: TEXT, fontSize: 15, fontFamily: 'sans-serif' }}>{row.name}</div>
                    <div style={fileNumStyle}>{row.fileNum}</div>
                    <div style={{ flex: 1, color: MUTED, fontSize: 13, fontFamily: 'monospace' }}>{row.period}</div>
                    <div style={{ flex: 1, color: MUTED, fontSize: 13, fontFamily: 'sans-serif' }}>{row.filingType}</div>
                    <div style={viewBtnStyle}>View Schedule →</div>
                  </div>
                );
              })}
            </div>

            {/* Auto-discovery note */}
            {frame >= 120 && (
              <div style={{
                padding: '14px 20px',
                background: 'rgba(99,102,241,0.06)',
                border: `1px solid ${BORDER}`,
                borderRadius: 10,
                color: MUTED,
                fontSize: 14,
                fontFamily: 'sans-serif',
                opacity: interpolate(frame, [120, 140], [0, 1], { extrapolateRight: 'clamp' }),
                transform: `translateY(${interpolate(frame, [120, 140], [12, 0], { extrapolateRight: 'clamp' })}px)`,
              }}>
                <span style={{ color: ACCENT, fontWeight: 600 }}>Auto-identified</span> by Investment Company Act file numbers (814-XXXXX) — no manual list maintenance required
              </div>
            )}
          </div>
        </AppChrome>
      </div>
    </div>
  );
};

// ─── Scene 5: Comparison ─────────────────────────────────────────────────────

const OLD_ITEMS = [
  'Manually search SEC EDGAR filing by filing',
  'No cross-fund comparison for the same asset',
  'Hard-coded BDC lists go stale quickly',
  'Parse raw NPORT-P XML by hand for cusip/value',
  'No aggregated view of historical positions',
];
const NEW_ITEMS = [
  'Full-text EFTS search across all NPORT-P filings',
  'Side-by-side cross-fund valuation comparison',
  'Auto-identify BDCs by 814- file numbers',
  'Automatic XML parsing: cusip, value, shares, pricingDate',
  'Complete 10-Q history per fund in one click',
];

const SceneComparison: React.FC<{ frame: number; fps: number }> = ({ frame, fps }) => {
  const titleS = spring({ frame: Math.max(0, frame), fps, config: { damping: 14, stiffness: 100 } });

  const containerStyle: React.CSSProperties = {
    position: 'absolute',
    inset: 0,
    background: BG,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '48px 80px',
    gap: 44,
  };
  const titleStyle: React.CSSProperties = {
    color: TEXT,
    fontSize: 52,
    fontWeight: 800,
    fontFamily: 'sans-serif',
    textAlign: 'center',
    opacity: titleS,
    transform: `translateY(${(1 - titleS) * 30}px)`,
  };
  const colsStyle: React.CSSProperties = {
    display: 'flex',
    gap: 36,
    width: '100%',
    maxWidth: 1400,
  };
  const cardStyle = (isNew: boolean): React.CSSProperties => ({
    flex: 1,
    background: isNew ? 'rgba(99,102,241,0.07)' : 'rgba(239,68,68,0.05)',
    border: `2px solid ${isNew ? 'rgba(99,102,241,0.45)' : 'rgba(239,68,68,0.3)'}`,
    borderRadius: 18,
    padding: '30px 36px',
    opacity: titleS,
  });
  const cardTitleStyle = (isNew: boolean): React.CSSProperties => ({
    fontSize: 20,
    fontWeight: 700,
    fontFamily: 'sans-serif',
    color: isNew ? ACCENT : DANGER,
    marginBottom: 24,
    textAlign: 'center',
    letterSpacing: 1,
    textTransform: 'uppercase',
  });
  const itemStyle = (s: number, isNew: boolean): React.CSSProperties => ({
    display: 'flex',
    alignItems: 'flex-start',
    gap: 14,
    marginBottom: 18,
    opacity: s,
    transform: `translateX(${(1 - s) * (isNew ? 16 : -16)}px)`,
  });
  const iconStyle = (isNew: boolean): React.CSSProperties => ({
    width: 24,
    height: 24,
    borderRadius: '50%',
    background: isNew ? 'rgba(99,102,241,0.2)' : 'rgba(239,68,68,0.15)',
    border: `2px solid ${isNew ? ACCENT : DANGER}`,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    fontSize: 12,
    color: isNew ? ACCENT : DANGER,
    fontWeight: 700,
    marginTop: 1,
  });
  const itemTextStyle: React.CSSProperties = {
    color: TEXT,
    fontSize: 18,
    fontFamily: 'sans-serif',
    lineHeight: 1.5,
  };

  return (
    <div style={containerStyle}>
      <div style={titleStyle}>
        The old way vs. <span style={{ color: ACCENT }}>Private Investment Analyzer</span>
      </div>
      <div style={colsStyle}>
        <div style={cardStyle(false)}>
          <div style={cardTitleStyle(false)}>✗ Manual Research</div>
          {OLD_ITEMS.map((item, i) => {
            const s = spring({ frame: Math.max(0, frame - 18 - i * 9), fps, config: { damping: 16, stiffness: 130 } });
            return (
              <div key={i} style={itemStyle(s, false)}>
                <div style={iconStyle(false)}>✗</div>
                <span style={itemTextStyle}>{item}</span>
              </div>
            );
          })}
        </div>
        <div style={cardStyle(true)}>
          <div style={cardTitleStyle(true)}>✓ With This Tool</div>
          {NEW_ITEMS.map((item, i) => {
            const s = spring({ frame: Math.max(0, frame - 18 - i * 9), fps, config: { damping: 16, stiffness: 130 } });
            return (
              <div key={i} style={itemStyle(s, true)}>
                <div style={iconStyle(true)}>✓</div>
                <span style={itemTextStyle}>{item}</span>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
};

// ─── Scene 6: End Card ────────────────────────────────────────────────────────

const SceneEndCard: React.FC<{ frame: number; fps: number }> = ({ frame, fps }) => {
  const titleS   = spring({ frame: Math.max(0, frame - 8),  fps, config: { damping: 14, stiffness: 120 } });
  const taglineS = spring({ frame: Math.max(0, frame - 20), fps, config: { damping: 14, stiffness: 120 } });
  const subS     = spring({ frame: Math.max(0, frame - 32), fps, config: { damping: 14, stiffness: 120 } });
  const badgesS  = spring({ frame: Math.max(0, frame - 44), fps, config: { damping: 14, stiffness: 120 } });

  const containerStyle: React.CSSProperties = {
    position: 'absolute',
    inset: 0,
    background: `radial-gradient(ellipse 65% 55% at 50% 50%, rgba(99,102,241,0.16) 0%, ${BG} 65%)`,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  };
  const particles = Array.from({ length: 22 }).map((_: unknown, i: number) => {
    const angle = (i / 22) * Math.PI * 2 + frame * 0.013;
    const r     = 340 + Math.sin(frame * 0.038 + i * 1.1) * 65;
    const pStyle: React.CSSProperties = {
      position: 'absolute',
      left: 960 + Math.cos(angle) * r,
      top:  540 + Math.sin(angle) * r,
      width: 4,
      height: 4,
      borderRadius: '50%',
      background: ACCENT,
      opacity: 0.2 + Math.sin(frame * 0.055 + i) * 0.18,
    };
    return <div key={i} style={pStyle} />;
  });
  const logoStyle: React.CSSProperties = {
    width: 88,
    height: 88,
    borderRadius: 22,
    background: `linear-gradient(135deg, ${ACCENT}, rgba(99,102,241,0.5))`,
    border: `2px solid ${ACCENT}`,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 40,
    marginBottom: 28,
    opacity: titleS,
    transform: `scale(${0.65 + titleS * 0.35})`,
  };
  const titleStyle: React.CSSProperties = {
    color: TEXT,
    fontSize: 76,
    fontWeight: 900,
    fontFamily: 'sans-serif',
    textAlign: 'center',
    margin: 0,
    letterSpacing: '-0.03em',
    opacity: titleS,
    transform: `translateY(${(1 - titleS) * 40}px)`,
  };
  const taglineStyle: React.CSSProperties = {
    color: ACCENT,
    fontSize: 26,
    fontFamily: 'sans-serif',
    fontWeight: 500,
    textAlign: 'center',
    marginTop: 18,
    opacity: taglineS,
    transform: `translateY(${(1 - taglineS) * 20}px)`,
  };
  const subStyle: React.CSSProperties = {
    color: MUTED,
    fontSize: 16,
    fontFamily: 'monospace',
    textAlign: 'center',
    marginTop: 14,
    opacity: subS,
  };
  const dividerStyle: React.CSSProperties = {
    width: 130,
    height: 2,
    background: `linear-gradient(90deg, transparent, ${ACCENT}, transparent)`,
    marginTop: 28,
    opacity: subS,
  };
  const badgesStyle: React.CSSProperties = {
    display: 'flex',
    gap: 14,
    marginTop: 32,
    opacity: badgesS,
    transform: `translateY(${(1 - badgesS) * 14}px)`,
  };
  const badgeStyle: React.CSSProperties = {
    background: SECONDARY,
    border: `1px solid ${BORDER}`,
    borderRadius: 8,
    padding: '10px 22px',
    color: MUTED,
    fontSize: 13,
    fontFamily: 'monospace',
  };

  return (
    <div style={containerStyle}>
      {particles}
      <div style={logoStyle}>📊</div>
      <h1 style={titleStyle}>Private Investment Analyzer</h1>
      <div style={taglineStyle}>Track how funds mark the same asset — across every NPORT-P filing</div>
      <div style={subStyle}>Node.js + Express · SEC EDGAR EFTS · NPORT-P XML Parser</div>
      <div style={dividerStyle} />
      <div style={badgesStyle}>
        {['NPORT-P Search', 'BDC 10-Q / 10-K', '814- Auto-Identify', 'Cross-Fund Valuation'].map((b) => (
          <div key={b} style={badgeStyle}>{b}</div>
        ))}
      </div>
    </div>
  );
};

// ─── Root composition ─────────────────────────────────────────────────────────

export const GeneratedDemo: React.FC<{ screenshotUrls: string[] }> = () => {
  const { fps } = useVideoConfig();
  const frame   = useCurrentFrame();

  const s1 = 0;
  const s2 = s1 + D_HOOK;
  const s3 = s2 + D_SEARCH;
  const s4 = s3 + D_HOLDINGS;
  const s5 = s4 + D_BDC;
  const s6 = s5 + D_COMPARISON;

  return (
    <AbsoluteFill style={{ background: BG }}>
      <Sequence from={s1} durationInFrames={D_HOOK}>
        <AbsoluteFill>
          <SceneHook frame={frame - s1} fps={fps} />
        </AbsoluteFill>
      </Sequence>

      <Sequence from={s2} durationInFrames={D_SEARCH}>
        <AbsoluteFill>
          <SceneSearch frame={frame - s2} fps={fps} />
        </AbsoluteFill>
      </Sequence>

      <Sequence from={s3} durationInFrames={D_HOLDINGS}>
        <AbsoluteFill>
          <SceneHoldings frame={frame - s3} fps={fps} />
        </AbsoluteFill>
      </Sequence>

      <Sequence from={s4} durationInFrames={D_BDC}>
        <AbsoluteFill>
          <SceneBDC frame={frame - s4} fps={fps} />
        </AbsoluteFill>
      </Sequence>

      <Sequence from={s5} durationInFrames={D_COMPARISON}>
        <AbsoluteFill>
          <SceneComparison frame={frame - s5} fps={fps} />
        </AbsoluteFill>
      </Sequence>

      <Sequence from={s6} durationInFrames={D_ENDCARD}>
        <AbsoluteFill>
          <SceneEndCard frame={frame - s6} fps={fps} />
        </AbsoluteFill>
      </Sequence>
    </AbsoluteFill>
  );
};
