/**
 * AUTO-GENERATED by generate-composition API — do not edit manually.
 * This file is overwritten on each "Generate Demo" call.
 * Placeholder version shown here; the real one is written by Claude.
 */
import React from "react";
import { AbsoluteFill, useCurrentFrame, useVideoConfig, spring, interpolate } from "remotion";

export const GENERATED_DURATION = 900;
export const GENERATED_FPS = 30;
export const GENERATED_WIDTH = 1920;
export const GENERATED_HEIGHT = 1080;

export const GeneratedDemo: React.FC<{ screenshotUrls: string[] }> = () => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();

  const s = spring({ frame, fps, config: { damping: 14, stiffness: 120 } });
  const opacity = s;
  const translateY = (1 - s) * 40;

  const pulse = 0.8 + Math.sin(frame * 0.08) * 0.2;

  return (
    <AbsoluteFill
      style={{
        background:     "#0a0a0f",
        display:        "flex",
        alignItems:     "center",
        justifyContent: "center",
        fontFamily:     "sans-serif",
      }}
    >
      {/* Radial glow */}
      <div
        style={{
          position:   "absolute",
          inset:      0,
          background: "radial-gradient(ellipse 60% 50% at 50% 50%, rgba(99,102,241,0.15) 0%, transparent 70%)",
        }}
      />

      <div
        style={{
          opacity,
          transform:  `translateY(${translateY}px)`,
          textAlign:  "center",
          zIndex:     1,
        }}
      >
        <div
          style={{
            fontSize:      "72px",
            fontWeight:    900,
            color:         "#6366f1",
            letterSpacing: "-0.03em",
            opacity:       pulse,
          }}
        >
          ✦
        </div>
        <div
          style={{
            fontSize:      "32px",
            fontWeight:    700,
            color:         "#f0f0f5",
            marginTop:     "16px",
            letterSpacing: "-0.01em",
          }}
        >
          Demo generating...
        </div>
        <div
          style={{
            fontSize:   "16px",
            color:      "#8888a8",
            marginTop:  "12px",
            fontFamily: "monospace",
          }}
        >
          Click &quot;Generate Demo&quot; to create your video
        </div>
      </div>

      {/* Bottom bar */}
      <div
        style={{
          position:   "absolute",
          bottom:     0,
          left:       0,
          right:      0,
          height:     "3px",
          background: `linear-gradient(90deg, transparent, #6366f1, transparent)`,
          opacity:    interpolate(frame, [0, 30], [0, 1], { extrapolateRight: "clamp" }),
        }}
      />
    </AbsoluteFill>
  );
};
